baseURL: http://dkeyserv.com/
languageCode: en-us
title: Distributed PGP Keyserver
theme: book

params:
  BookMenuBundle: /menu

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1